// JsFromRoutes CacheKey 3bde55e902dbbb4e540fa07846043c35
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as deviseSessions } from './Devise/SessionsApi'
export { default as devisePasswords } from './Devise/PasswordsApi'
export { default as deviseRegistrations } from './Devise/RegistrationsApi'
export { default as home } from './HomeApi'
export { default as players } from './PlayersApi'
export { default as turns } from './TurnsApi'
export { default as games } from './GamesApi'
