// JsFromRoutes CacheKey c5d5a76886786a8b18aeee58df5c9188
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/games'),
  create: /* #__PURE__ */ definePathHelper('post', '/games'),
  show: /* #__PURE__ */ definePathHelper('get', '/games/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/games/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/games/:id'),
}
