// JsFromRoutes CacheKey 00d8197d6d9f913434b1b341ff4355e6
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  destroy: /* #__PURE__ */ definePathHelper('delete', '/games/:game_id/players'),
  create: /* #__PURE__ */ definePathHelper('post', '/games/:game_id/players'),
}
