// JsFromRoutes CacheKey 6a85eba75e9a0c1a0fc7aefa122ca8ec
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/games/:game_id/turn'),
}
